/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppAnnouncementsRouteImport } from './routes/_authenticated/_app/announcements'
import { Route as AuthenticatedAppAssignmentsRouteImport } from './routes/_authenticated/_app/assignments'
import { Route as AuthenticatedAppAttendanceRouteImport } from './routes/_authenticated/_app/attendance'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppExamsRouteImport } from './routes/_authenticated/_app/exams'
import { Route as AuthenticatedAppNotesRouteImport } from './routes/_authenticated/_app/notes'
import { Route as AuthenticatedAppPerformanceRouteImport } from './routes/_authenticated/_app/performance'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/_app/tasks'
import { Route as AuthenticatedAppTimetableRouteImport } from './routes/_authenticated/_app/timetable'
import { Route as AuthenticatedAppSubjectsIndexRouteImport } from './routes/_authenticated/_app/subjects.index'
import { Route as AuthenticatedAppSubjectsSubjectIdRouteImport } from './routes/_authenticated/_app/subjects.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAnnouncementsRoute =
  AuthenticatedAppAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAssignmentsRoute =
  AuthenticatedAppAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAttendanceRoute =
  AuthenticatedAppAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppExamsRoute = AuthenticatedAppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppNotesRoute = AuthenticatedAppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPerformanceRoute =
  AuthenticatedAppPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTimetableRoute =
  AuthenticatedAppTimetableRouteImport.update({
    id: '/timetable',
    path: '/timetable',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSubjectsIndexRoute =
  AuthenticatedAppSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSubjectsSubjectIdRoute =
  AuthenticatedAppSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/exams': typeof AuthenticatedAppExamsRoute
  '/notes': typeof AuthenticatedAppNotesRoute
  '/performance': typeof AuthenticatedAppPerformanceRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/tasks': typeof AuthenticatedAppTasksRoute
  '/timetable': typeof AuthenticatedAppTimetableRoute
  '/subjects/$subjectId': typeof AuthenticatedAppSubjectsSubjectIdRoute
  '/subjects/': typeof AuthenticatedAppSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/exams': typeof AuthenticatedAppExamsRoute
  '/notes': typeof AuthenticatedAppNotesRoute
  '/performance': typeof AuthenticatedAppPerformanceRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/tasks': typeof AuthenticatedAppTasksRoute
  '/timetable': typeof AuthenticatedAppTimetableRoute
  '/subjects/$subjectId': typeof AuthenticatedAppSubjectsSubjectIdRoute
  '/subjects': typeof AuthenticatedAppSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/_authenticated/_app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/_authenticated/_app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/exams': typeof AuthenticatedAppExamsRoute
  '/_authenticated/_app/notes': typeof AuthenticatedAppNotesRoute
  '/_authenticated/_app/performance': typeof AuthenticatedAppPerformanceRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/_app/timetable': typeof AuthenticatedAppTimetableRoute
  '/_authenticated/_app/subjects/$subjectId': typeof AuthenticatedAppSubjectsSubjectIdRoute
  '/_authenticated/_app/subjects/': typeof AuthenticatedAppSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/dashboard'
    | '/exams'
    | '/notes'
    | '/performance'
    | '/settings'
    | '/tasks'
    | '/timetable'
    | '/subjects/$subjectId'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/dashboard'
    | '/exams'
    | '/notes'
    | '/performance'
    | '/settings'
    | '/tasks'
    | '/timetable'
    | '/subjects/$subjectId'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/announcements'
    | '/_authenticated/_app/assignments'
    | '/_authenticated/_app/attendance'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/exams'
    | '/_authenticated/_app/notes'
    | '/_authenticated/_app/performance'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/tasks'
    | '/_authenticated/_app/timetable'
    | '/_authenticated/_app/subjects/$subjectId'
    | '/_authenticated/_app/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/announcements': {
      id: '/_authenticated/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAppAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/assignments': {
      id: '/_authenticated/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAppAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/attendance': {
      id: '/_authenticated/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAppAttendanceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/exams': {
      id: '/_authenticated/_app/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedAppExamsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/notes': {
      id: '/_authenticated/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedAppNotesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/performance': {
      id: '/_authenticated/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedAppPerformanceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/tasks': {
      id: '/_authenticated/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/timetable': {
      id: '/_authenticated/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedAppTimetableRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/subjects/': {
      id: '/_authenticated/_app/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedAppSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/subjects/$subjectId': {
      id: '/_authenticated/_app/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof AuthenticatedAppSubjectsSubjectIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAnnouncementsRoute: typeof AuthenticatedAppAnnouncementsRoute
  AuthenticatedAppAssignmentsRoute: typeof AuthenticatedAppAssignmentsRoute
  AuthenticatedAppAttendanceRoute: typeof AuthenticatedAppAttendanceRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppExamsRoute: typeof AuthenticatedAppExamsRoute
  AuthenticatedAppNotesRoute: typeof AuthenticatedAppNotesRoute
  AuthenticatedAppPerformanceRoute: typeof AuthenticatedAppPerformanceRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppTimetableRoute: typeof AuthenticatedAppTimetableRoute
  AuthenticatedAppSubjectsSubjectIdRoute: typeof AuthenticatedAppSubjectsSubjectIdRoute
  AuthenticatedAppSubjectsIndexRoute: typeof AuthenticatedAppSubjectsIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAnnouncementsRoute: AuthenticatedAppAnnouncementsRoute,
  AuthenticatedAppAssignmentsRoute: AuthenticatedAppAssignmentsRoute,
  AuthenticatedAppAttendanceRoute: AuthenticatedAppAttendanceRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppExamsRoute: AuthenticatedAppExamsRoute,
  AuthenticatedAppNotesRoute: AuthenticatedAppNotesRoute,
  AuthenticatedAppPerformanceRoute: AuthenticatedAppPerformanceRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppTimetableRoute: AuthenticatedAppTimetableRoute,
  AuthenticatedAppSubjectsSubjectIdRoute:
    AuthenticatedAppSubjectsSubjectIdRoute,
  AuthenticatedAppSubjectsIndexRoute: AuthenticatedAppSubjectsIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
