/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppAssignmentsRouteImport } from './routes/_authenticated/_app/assignments'
import { Route as AuthenticatedAppAttendanceRouteImport } from './routes/_authenticated/_app/attendance'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppExamsRouteImport } from './routes/_authenticated/_app/exams'
import { Route as AuthenticatedAppTimetableRouteImport } from './routes/_authenticated/_app/timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAssignmentsRoute =
  AuthenticatedAppAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAttendanceRoute =
  AuthenticatedAppAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppExamsRoute = AuthenticatedAppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTimetableRoute =
  AuthenticatedAppTimetableRouteImport.update({
    id: '/timetable',
    path: '/timetable',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/exams': typeof AuthenticatedAppExamsRoute
  '/timetable': typeof AuthenticatedAppTimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/exams': typeof AuthenticatedAppExamsRoute
  '/timetable': typeof AuthenticatedAppTimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/_authenticated/_app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/exams': typeof AuthenticatedAppExamsRoute
  '/_authenticated/_app/timetable': typeof AuthenticatedAppTimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/assignments'
    | '/attendance'
    | '/dashboard'
    | '/exams'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/assignments'
    | '/attendance'
    | '/dashboard'
    | '/exams'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/assignments'
    | '/_authenticated/_app/attendance'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/exams'
    | '/_authenticated/_app/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/assignments': {
      id: '/_authenticated/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAppAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/attendance': {
      id: '/_authenticated/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAppAttendanceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/exams': {
      id: '/_authenticated/_app/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedAppExamsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/timetable': {
      id: '/_authenticated/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedAppTimetableRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAssignmentsRoute: typeof AuthenticatedAppAssignmentsRoute
  AuthenticatedAppAttendanceRoute: typeof AuthenticatedAppAttendanceRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppExamsRoute: typeof AuthenticatedAppExamsRoute
  AuthenticatedAppTimetableRoute: typeof AuthenticatedAppTimetableRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAssignmentsRoute: AuthenticatedAppAssignmentsRoute,
  AuthenticatedAppAttendanceRoute: AuthenticatedAppAttendanceRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppExamsRoute: AuthenticatedAppExamsRoute,
  AuthenticatedAppTimetableRoute: AuthenticatedAppTimetableRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
